name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "[Start Login]"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "[End Login]"
        
    - name: Build Image
      run: |
        docker build -t juanfalcon/docker-graphql-example:0.0.1 .
        docker build -t juanfalcon/docker-graphql-example .
        
    - name: Push Image
      run: |
        docker push juanfalcon/docker-graphql-example:0.0.1
        docker push juanfalcon/docker-graphql-example
    
